name: Trainee User Theme
description: User theme
type: theme
core_version_requirement: ^8 || ^9
package: Trainee custom themes
libraries:
  - trainee/global-styling

base theme: classy
regions:
  branding: Branding
  navigation: Main navigation
  search: Search
  featured: Featured
  content: Content
  right_sidebar: Right sidebar
  footer_first: Footer First
  footer_second: Footer Second
  footer_third: Footer Third
  footer_bottom: Footer bottom
