<?php
/**
 * @file
 * Primary module hooks for pokemon module.
 */

use Drupal\advancedqueue\Entity\Queue;
use Drupal\advancedqueue\Job;
use Drupal\pokemon\PokemonManager;

/**
 * The callback for the cron job.
 */
function pokemon_ability_tax_callback() {
  /** @var \Drupal\pokemon\PokemonManager $pokemon_manager */
  $pokemon_manager = \Drupal::service('pokemon.pokemon_manager');

  $description = PokemonManager::getTaxonomyEndpoints()['ability'];

  $list = $pokemon_manager->getResourceList('ability', PokemonManager::MAX_LIMIT);

  $payload = [
    'endpoint' => 'ability',
    'description' => $description,
    'list' => $list,
  ];
  $job = Job::create('pokemons_import_job', $payload);
  if ($job instanceof Job) {
    $q = Queue::load('import_ability');
    $q->enqueueJob($job);
  }

  \Drupal::logger('custom_utility')->notice('ability cron job ended');


  // В данном кроне мы должны вытянуть список всех абилити и добавить в очередь нужный тип джобы с определенным пэйлоадом
}
