<?php

/**
 * @file
 * Primary module hooks for advertisement module.
 */

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function advertisement_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($entity_type->id() == 'node' && $bundle == 'advertising_request') {
    if (isset($fields['field_advertisement_title'])) {
      $fields['field_advertisement_title']->addConstraint('AdvertisementTitleConstraint');
    }
  }
}
