trainee_user.settings:
  type: config_object
  label: 'Module settings'
  mapping:
    api_base_url:
      type: string
      label: 'API Base URL'
    api_token:
      type: string
      label: 'API Access-Token'
    header_content_type:
      type: string
      label: 'Header Content-Type'
    header_accept:
      type: string
      label: 'Header Accept'
