trainee_user.settings:
  type: config_object
  label: 'Module settings'
  mapping:
    api_base_url:
      type: string
      label: 'API Base URL'
    api_token:
      type: string
      label: 'API Access-Token'
    header_content_type:
      type: string
      label: 'Header Content-Type'
    header_accept:
      type: string
      label: 'Header Accept'
block.settings.trainee_user_user_table_block:
  type: block_settings
  label: 'Configuration of user table block'
  mapping:
    page:
      type: integer
      label: 'The page of user table'
field.value.user_reference_field:
  type: mapping
  label: 'External user'
  mapping:
    external_user_id:
      type: integer
      label: 'External user id'
