trainee_user.users:
  path: 'users'
  defaults:
    _controller: 'Drupal\trainee_user\Controller\UserController::users'
    _title: 'Trainee User form'
  requirements:
    _permission: 'access content'
