trainee_user.api_config_page:
  path: '/admin/config/users-api'
  defaults:
    _form: 'Drupal\trainee_user\Form\UserApiConfigForm'
    _title: 'User API Settings'
  requirements:
    _permission: 'administer site configuration'

trainee_user.user_list:
  path: 'users-page/{page}'
  defaults:
    _controller: 'Drupal\trainee_user\Controller\UserController::showUserList'
    _title: 'List of Users'
  requirements:
    _permission: 'access content'

trainee_user.management_form:
  path: 'form'
  defaults:
    _form: 'Drupal\trainee_user\Form\UserManagementForm'
    _title: 'Trainee user form'
  requirements:
    _permission: 'access content'

trainee_user.delete_form:
  path: 'delete/{id}'
  defaults:
    _form: 'Drupal\trainee_user\Form\UserDeleteForm'
    _title: 'Trainee user form'
  requirements:
    _permission: 'access content'

trainee_user.external_user_autocomplete:
  path: '/admin/user/autocomplete'
  defaults:
    _controller: 'Drupal\trainee_user\Controller\UserController::handleEmailAutocomplete'
  requirements:
    _permission: 'administer content types'
