minute.settings:
  type: config_object
  label: 'Module settings'
  mapping:
    even_title:
      type: string
      label: 'Text for Even Tile'
    odd_title:
      type: string
      label: 'Text for Odd Tile'
