global-styling:
  version: 1.x
  js:
    js/main.js: {}
    'https://code.jquery.com/jquery-3.4.1.min.js':
      { type: external, minified: true }
    'https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js':
      { type: external, minified: true }
  css:
    theme:
      css/style.css: {}
      css/bootstrap.min.css: {}

      # Icon Font Stylesheet
      'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.0/css/all.min.css':
        { type: external, minified: true }
      'https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css':
        { type: external, minified: true }

      # Google Web Fonts
      'https://fonts.gstatic.com':
        { type: external, minified: true }
      'https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@400;700&family=Roboto:wght@400;700&display=swap':
        { type: external, minified: true }

# easing
easing:
  version: 1.x
  js:
    lib/easing/easing.min.js: {}

# owlcarousel
owlcarousel:
  version: 1.x
  css:
    theme:
      lib/owlcarousel/assets/owl.carousel.css: {}
      lib/owlcarousel/assets/owl.theme.default.css: {}
      lib/owlcarousel/assets/owl.theme.green.css: {}
  js:
      lib/owlcarousel/owl.carousel.min.js: {}

# tempusodominus
tempusodominus:
  version: 1.x
  css:
    theme:
      lib/tempusodominus/tempusdominus-bootstrap-4.min.css: {}
  js:
    lib/tempusodominus/js/moment.min.js: {}
    lib/tempusodominus/js/moment-timezone.min.js: {}
    lib/tempusodominus/js/tempusdominus-bootstrap-4.min.js: {}

# waypoints
waypoints:
  version: 1.x
  js:
    lib/waypoints/waypoints.min.js: {}
